### ISSUE TITLE
Automatically upload release jars

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#831]
Upon new releases, the jar is generated but not automatically uploaded to the GitHub releases entry. This functionality should be added.

**Comment by germanattanasio** [comment]
This is what you need

```
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
    deploy:
      provider: releases
      api_key: "GITHUB OAUTH TOKEN"
      file: "FILE TO UPLOAD"
      skip_cleanup: true
```

More info: https://docs.travis-ci.com/user/deployment/releases/
